iter1: Авторизация, аутентификация. Начало создания заказа.
kosalnik/gmarket pull request #2
Opened 2024-05-28 20:54 UTC by kosalnik

Наброски обработки с accrual.

2024-05-30 07:16 UTC, kosalnik commented
Прошу прощения за хаос. Профукал дедлайн. Нужно было торопиться (:

2024-06-04 10:09 UTC, rktkov requested changes

2024-06-04 10:09 UTC, rktkov commented on internal/application/server.go
> +	userService    *service.UserService
Это должен быть интерфейс

2024-06-04 10:09 UTC, rktkov commented on internal/application/server.go
> +	orderService   *service.OrderService
Это тоже должен быть интерфейс

2024-06-05 07:19 UTC, kosalnik commented on internal/application/server.go
> +	orderService   *service.OrderService
fixed

2024-06-05 07:19 UTC, kosalnik commented on internal/application/server.go
> +	userService    *service.UserService
fixed

2024-06-11 10:08 UTC, edylcrm approved these changes

2024-06-11 10:08 UTC, edylcrm commented on internal/infra/postgres/repository.go
> +package postgres
Чаще вижу реализации когда для каждой отдельной сущности создается свой repository. Со временем монорепориторий становится слишком большим и с ним становится не очень удобно работать. Но тут на любителя :)

2024-06-11 10:08 UTC, edylcrm commented on pkg/domain/entity/account.go
> +package entity
Вообще в pkg размещают функционал который может использоваться в других проектах/репозиториях. Точно ли доменные модели должны быть здесь?

2024-06-11 10:11 UTC, edylcrm approved these changes

2024-06-11 10:23 UTC, kosalnik commented on pkg/domain/entity/account.go
> +package entity
я их тут разместил чтобы мне go по рукам бил, если я из pkg полезу вдруг в internal

2024-08-17 08:00 UTC, merged